# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-10 19:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolBoardAgendas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_at', models.DateTimeField()),
                ('link_to_agenda', models.TextField()),
                ('keyword_flag', models.BooleanField()),
                ('keywords', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolDistrict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url_to_scrape', models.TextField()),
                ('grade_levels', models.CharField(max_length=50, null=True)),
                ('mailing_city', models.CharField(max_length=60)),
                ('mailing_state', models.CharField(max_length=2)),
                ('district_number', models.CharField(max_length=4, null=True)),
                ('can_parse', models.BooleanField(default=False)),
                ('ever_matched_keywords', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='schoolboardagendas',
            name='school_district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolboardagendas.SchoolDistrict'),
        ),
    ]
